# Pre-commit configuration
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^(tests/|notebooks/|scripts/|app/services/legacy_page_analyzer/|app/services/page_analyzer/|app/services/segmentation_service\.py|app/services/page_segmentation/|app/api/routes/segmentation\.py)
      - id: ruff-format

# Removed black and isort - ruff handles both formatting and import sorting

# Temporarily disable mypy for legacy code - too many type errors
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.16.1
#    hooks:
#      - id: mypy
#        additional_dependencies: [types-PyYAML, types-requests, types-python-dateutil]
#        exclude: ^(tests/|scripts/|app/services/legacy_page_analyzer/|app/services/page_analyzer/|app/services/segmentation_service\.py|app/services/page_segmentation/|app/api/routes/segmentation\.py)
